"""empty message

Revision ID: 20b6ecc066bc
Revises: 3941d49605c
Create Date: 2015-04-09 20:11:11.284833

"""

# revision identifiers, used by Alembic.
revision = '20b6ecc066bc'
down_revision = '3941d49605c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
