"""empty message

Revision ID: 3dfad15d1d5e
Revises: 20b6ecc066bc
Create Date: 2015-04-11 05:34:01.438014

"""

# revision identifiers, used by Alembic.
revision = '3dfad15d1d5e'
down_revision = '20b6ecc066bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
